/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CopyUrlInPreview
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/helpers.ts
var loadImageBlobTimeout = 5e3;
function withTimeout(ms, promise) {
  const timeout = new Promise((resolve, reject) => {
    const id = setTimeout(() => {
      clearTimeout(id);
      reject(`timed out after ${ms} ms`);
    }, ms);
  });
  return Promise.race([
    promise,
    timeout
  ]);
}
function loadImageBlob(imgSrc) {
  return __async(this, null, function* () {
    const loadImageBlobCore = () => {
      return new Promise((resolve, reject) => {
        const image = new Image();
        image.crossOrigin = "anonymous";
        image.onload = () => {
          const canvas = document.createElement("canvas");
          canvas.width = image.width;
          canvas.height = image.height;
          const ctx = canvas.getContext("2d");
          ctx.drawImage(image, 0, 0);
          canvas.toBlob((blob) => {
            resolve(blob);
          });
        };
        image.onerror = () => __async(this, null, function* () {
          try {
            yield fetch(image.src, { "mode": "no-cors" });
            const blob = yield loadImageBlob(`https://api.allorigins.win/raw?url=${encodeURIComponent(imgSrc)}`);
            resolve(blob);
          } catch (e) {
            reject();
          }
        });
        image.src = imgSrc;
      });
    };
    return withTimeout(loadImageBlobTimeout, loadImageBlobCore());
  });
}
function onElement(el, event, selector, listener, options) {
  el.on(event, selector, listener, options);
  return () => el.off(event, selector, listener, options);
}

// src/main.ts
var IMAGE_URL_PREFIX = "/_capacitor_file_";
var SUCCESS_NOTICE_TIMEOUT = 1800;
var longTapTimeout = 500;
var deleteTempFileTimeout = 6e4;
var OPEN_PDF_MENU_BORDER_SIZE = 100;
var OPEN_PDF_MENU_TIMEOUT = 5e3;
var CopyUrlInPreview = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.longTapTimeoutId = null;
  }
  onload() {
    this.registerDocument(document);
    app.workspace.on("window-open", (workspaceWindow, window2) => {
      this.registerDocument(window2.document);
    });
  }
  registerDocument(document2) {
    this.register(onElement(document2, "contextmenu", "a.external-link", this.onClick.bind(this)));
    this.register(onElement(document2, "mouseover", ".pdf-embed iframe, .pdf-embed div.pdf-container, .workspace-leaf-content[data-type=pdf] iframe", this.showOpenPdfMenu.bind(this)));
    this.register(onElement(document2, "mousemove", ".pdf-canvas", this.showOpenPdfMenu.bind(this)));
    if (import_obsidian.Platform.isDesktop) {
      this.register(onElement(document2, "contextmenu", "img", this.onClick.bind(this)));
      this.register(onElement(document2, "mouseover", ".cm-link, .cm-hmd-internal-link", this.storeLastHoveredLinkInEditor.bind(this)));
      this.register(onElement(document2, "mouseover", "a.internal-link", this.storeLastHoveredLinkInPreview.bind(this)));
    } else {
      this.register(onElement(document2, "touchstart", "img", this.startWaitingForLongTap.bind(this)));
      this.register(onElement(document2, "touchend", "img", this.stopWaitingForLongTap.bind(this)));
      this.register(onElement(document2, "touchmove", "img", this.stopWaitingForLongTap.bind(this)));
    }
  }
  storeLastHoveredLinkInEditor(event) {
    var _a;
    const editor = (_a = app.workspace.getActiveViewOfType(import_obsidian.MarkdownView)) == null ? void 0 : _a.editor;
    if (!editor) {
      return;
    }
    const position = editor.posAtMouse(event);
    const token = editor.getClickableTokenAt(position);
    if (!token) {
      return;
    }
    this.lastHoveredLinkTarget = token.text;
  }
  storeLastHoveredLinkInPreview(event, link) {
    this.lastHoveredLinkTarget = link.getAttribute("data-href");
  }
  showOpenPdfMenu(event, el) {
    var _a;
    if (this.openPdfMenu || this.preventReopenPdfMenu) {
      return;
    }
    const rect = el.getBoundingClientRect();
    if (rect.left + OPEN_PDF_MENU_BORDER_SIZE < event.x && event.x < rect.right - OPEN_PDF_MENU_BORDER_SIZE && rect.top + OPEN_PDF_MENU_BORDER_SIZE < event.y && event.y < rect.bottom - OPEN_PDF_MENU_BORDER_SIZE) {
      return;
    }
    const pdfEmbed = el.closest(".pdf-embed");
    let pdfFile;
    if (pdfEmbed) {
      let pdfLink = "";
      if (pdfEmbed.hasClass("popover")) {
        pdfLink = this.lastHoveredLinkTarget;
      } else {
        pdfLink = (_a = pdfEmbed.getAttr("src")) != null ? _a : "";
      }
      pdfLink = pdfLink == null ? void 0 : pdfLink.replace(/#page=\d+$/, "");
      const currentNotePath = this.app.workspace.getActiveFile().path;
      pdfFile = this.app.metadataCache.getFirstLinkpathDest(pdfLink, currentNotePath);
    } else {
      pdfFile = this.app.workspace.getActiveFile();
    }
    const menu = new import_obsidian.Menu();
    this.registerEscapeButton(menu);
    menu.onHide(() => this.openPdfMenu = null);
    menu.addItem((item) => item.setIcon("pdf-file").setTitle("Open PDF externally").onClick(() => __async(this, null, function* () {
      this.preventReopenPdfMenu = true;
      setTimeout(() => {
        this.preventReopenPdfMenu = false;
      }, OPEN_PDF_MENU_TIMEOUT);
      this.hideOpenPdfMenu();
      if (import_obsidian.Platform.isDesktop) {
        yield this.app.openWithDefaultApp(pdfFile.path);
      } else {
        yield this.app.vault.adapter.open(pdfFile.path);
      }
    })));
    menu.showAtMouseEvent(event);
    this.openPdfMenu = menu;
    setTimeout(this.hideOpenPdfMenu.bind(this), OPEN_PDF_MENU_TIMEOUT);
  }
  registerEscapeButton(menu, document2 = activeDocument) {
    menu.register(onElement(document2, "keydown", "*", (e) => {
      if (e.key === "Escape") {
        e.preventDefault();
        e.stopPropagation();
        menu.hide();
      }
    }));
  }
  hideOpenPdfMenu() {
    if (this.openPdfMenu) {
      this.openPdfMenu.hide();
    }
  }
  startWaitingForLongTap(event, img) {
    if (this.longTapTimeoutId) {
      clearTimeout(this.longTapTimeoutId);
      this.longTapTimeoutId = null;
    } else {
      if (event.targetTouches.length == 1) {
        this.longTapTimeoutId = window.setTimeout(this.processLongTap.bind(this, event, img), longTapTimeout);
      }
    }
  }
  stopWaitingForLongTap() {
    if (this.longTapTimeoutId) {
      clearTimeout(this.longTapTimeoutId);
      this.longTapTimeoutId = null;
    }
  }
  processLongTap(event, img) {
    return __async(this, null, function* () {
      event.stopPropagation();
      this.longTapTimeoutId = null;
      const adapter = this.app.vault.adapter;
      const electronWindow = window;
      const basePath = adapter.getFullPath("");
      const webviewServerUrl = electronWindow.WEBVIEW_SERVER_URL;
      const localImagePrefixUrl = webviewServerUrl + IMAGE_URL_PREFIX + basePath;
      if (img.src.startsWith(localImagePrefixUrl)) {
        const encodedImageFileRelativePath = img.src.replace(localImagePrefixUrl, "");
        const imageFileRelativePath = decodeURIComponent(encodedImageFileRelativePath);
        yield adapter.open(imageFileRelativePath);
      } else {
        try {
          const blob = yield loadImageBlob(img.src);
          if (!blob.type.startsWith("image/")) {
            new import_obsidian.Notice(`Unsupported mime type ${blob.type}`);
            return;
          }
          const extension = blob.type.replace("image/", "");
          const randomGuid = window.URL.createObjectURL(new Blob([])).split("/").pop();
          const tempFileName = `/.temp-${randomGuid}.${extension}`;
          const buffer = yield blob.arrayBuffer();
          yield adapter.writeBinary(tempFileName, buffer);
          setTimeout(() => adapter.remove(tempFileName), deleteTempFileTimeout);
          new import_obsidian.Notice("Image was temporarily saved and will be removed in 1 minute");
          yield adapter.open(tempFileName);
        } catch (e) {
          new import_obsidian.Notice("Cannot open image");
        }
      }
    });
  }
  onClick(event) {
    event.preventDefault();
    const target = event.target;
    const imgType = target.localName;
    const menu = new import_obsidian.Menu();
    switch (imgType) {
      case "img": {
        const image = target.currentSrc;
        const thisURL = new URL(image);
        const Proto = thisURL.protocol;
        switch (Proto) {
          case "app:":
          case "data:":
          case "http:":
          case "https:":
            menu.addItem((item) => item.setIcon("image-file").setTitle("Copy image to clipboard").onClick(() => __async(this, null, function* () {
              try {
                const blob = yield loadImageBlob(image);
                const data = new ClipboardItem({ [blob.type]: blob });
                yield navigator.clipboard.write([data]);
                new import_obsidian.Notice("Image copied to the clipboard!", SUCCESS_NOTICE_TIMEOUT);
              } catch (e) {
                new import_obsidian.Notice("Error, could not copy the image!");
              }
            })));
            break;
          default:
            new import_obsidian.Notice(`no handler for ${Proto} protocol`);
            return;
        }
        break;
      }
      case "a": {
        const link = target.href;
        menu.addItem((item) => item.setIcon("link").setTitle("Copy URL").onClick(() => {
          navigator.clipboard.writeText(link);
          new import_obsidian.Notice("URL copied to your clipboard", SUCCESS_NOTICE_TIMEOUT);
        }));
        break;
      }
      default:
        new import_obsidian.Notice("No handler for this image type!");
        return;
    }
    this.registerEscapeButton(menu);
    menu.showAtPosition({ x: event.pageX, y: event.pageY });
    this.app.workspace.trigger("copy-url-in-preview:contextmenu", menu);
  }
};
